수정중...위설록 모델링 구현 (Create : wesulloc modeling)
wecode-bootcamp-korea/33-1st-Wesulloc-backend pull request #2
Opened 2022-05-24 12:59 UTC by jhwang0801

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-25 08:41 UTC, lordmyshepherd requested changes

2022-05-25 08:41 UTC, lordmyshepherd commented on products/models.py
> +        unique_together = ('user', 'product')
unique 설정 잘 해주셨습니다!!
다만, 공식 문서에서는 `unique_together` 보다는 `UniqueConstraint`을 사용하도록 권장하고 있습니다!
수정해주세요-!

![image](https://user-images.githubusercontent.com/53214510/170219708-e2e120c1-de46-4ffb-bf9d-531a761b652b.png)

2022-05-25 08:41 UTC, lordmyshepherd commented on users/models.py
> +        abstract = True
공통으로 사용되는 TimeStampModel class가 users/models.py 안에 포함되어 있습니다.
모든 models.py에서 공통으로 사용되는 모듈은 core/models.py를 별도로 만들어서 관리하는게 좋겠습니다-!
(core app을 만들면 좋겠다는 의미입니다.)

2022-05-25 11:13 UTC, jhwang0801 commented on products/models.py
> +        unique_together = ('user', 'product')
리뷰 감사합니다!!
해당 내용 UniqueConstraint 사용해서 다시 작성했습니다!

2022-05-25 11:14 UTC, jhwang0801 commented on users/models.py
> +        abstract = True
추후 프로젝트 진행 때도 동일하게 공통적으로 사용되는 모듈은 별도로 관리하도록 하겠습니다!
리뷰 감사합니다~!

2022-05-26 01:09 UTC, lordmyshepherd commented
LGTM 👍🏻 깔끔합니다!

2022-05-26 01:09 UTC, merged

2022-05-26 01:09 UTC, jhwang0801 commented
오늘 오전에 추가적으로 Review Class에 평점관련하여 rating을 아래와 같이 추가하였습니다.
````
class Review(models.Model):
    rating      = models.DecimalField(max_digits=2, decimal_places=1)
```

평점을 소수점 한자리 까지 구현할 생각입니다.