[33기 팀 위설록] 제품 리스트 (Product List View) 수정중
wecode-bootcamp-korea/33-1st-Wesulloc-backend pull request #5
Opened 2022-05-28 04:08 UTC by jhwang0801

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-28 09:23 UTC, jhwang0801 commented
PR 작성 후, 코드에 있는 문제점을 발견하였지만 해결법을 못찾고 있습니다.

2022-05-28 11:33 UTC, jhwang0801 commented on products/views.py
> +                        .order_by(sort_type.get(sort))[offset:offset+limit]
해당 코드를 통해서 "판매량순" 이라는 필터링을 지정해주려 하였고,
`total_sales=Count('orderitem__id') * F('orderitem__quantity')` 로 초기에 코드를 작성하였으나,

OrderItem table의 DB 값을 아래 사진과 같이 입력한 후 POSTMAN을 통해 확인해보니 사진과 같이 product_id =1 인 제품이 2번 출력이 되는 오류가 나타나고 있습니다.

![image](https://user-images.githubusercontent.com/75832544/170823561-54598cc8-2297-4fb7-b057-ca7e6060eaf1.png)
![image](https://user-images.githubusercontent.com/75832544/170823567-eee4f6a8-feff-455f-b73f-5c7734d95dc0.png)

해당 오류를 바로 잡고자 `total_sales=Count('orderitem__quantity')` 로 코드를 변경해 보았으나,
애초에 Count함수 자체로는 해결할 수 없는 문제로 판단되고,
의도하는 바는 ((주문상품) * (주문상품의 주문물량)) 을 출력하고자 했으나 방법을 찾지 못해 멘토님들의 조언을 부탁드리고 싶습니다.

2022-05-29 05:05 UTC, jhwang0801 commented on products/views.py
> +                        .order_by(sort_type.get(sort))[offset:offset+limit]
해당 문제 해결 완료하였습니다.


`products = Product.objects.filter(q).annotate(total_sales=Sum('orderitem__quantity', distinct=True)).annotate(total_reviews=Count('review__id', distinct=True)).order_by(sort_type.get(sort))[offset:offset+limit]`

2022-05-30 01:57 UTC, lordmyshepherd requested changes

2022-05-30 01:57 UTC, lordmyshepherd commented on products/urls.py
> +    path('/list', ProductListView.as_view()),
wesulloc/urls.py에 path 설정이 products로 되어 있기 때문에, `producuts/list` 보다는 `products` 만으로 충분히 목록을 호출하는지 알 수 있을 것 같습니다.
```suggestion
    path('', ProductListView.as_view()),
```

2022-05-30 01:57 UTC, lordmyshepherd commented on products/views.py
> +                        .order_by(sort_type.get(sort))[offset:offset+limit]
재승님! 문제 해결 정말 잘 해주셨습니다! 💯 💯 

ORM 구현을 정말 잘 해주셨습니다! 
마지막으로는 ORM이 왜 원하는데로 동작하지 않았는지 raw query문으로 분석해보시면 더 많은 도움이 될 것 같습니다!
1차 프로젝트가 끝나고 고민해보시면 좋을 것 같아서 의견 남겨 놓습니다!

- CASE 1. query문 실행시 table join이 어떻게 이루어지길래 데이터가 중복 출력되는지? (LEFT OUTER JOIN ? RIGHT OUTER JOIN?)
```python
total_sales=Count('orderitem__id') * F('orderitem__quantity')
```

- CASE 2.
```python
products = Product.objects.filter(q)\
        .annotate(total_sales=Sum('orderitem__quantity'))\
        .annotate(total_reviews=Count('review__id'))\
        .order_by(sort_type.get(sort))[offset:offset+limit]
```

- CASE 3.
```python
products = Product.objects.filter(q)\
        .annotate(total_sales=Sum('orderitem__quantity', distinct=True))\
        .annotate(total_reviews=Count('review__id', distinct=True))\
        .order_by(sort_type.get(sort))[offset:offset+limit]
```

2022-05-30 01:57 UTC, lordmyshepherd commented on products/views.py
> +            offset        = int(request.GET.get('offset',0))
offset, limit 👍🏻 

대부분 목록을 반환하는 엔드포인트에는 limit과 offset을 필요로 합니다. 그 이유는 앞에 PR template에 작성해 놓으신 것과 같이 한 번에 호출할 수 있는 개수를 제한하는 것에 있습니다. 
한번에 모든 데이터를 조회한다면 데이터베이스 뿐만 아니라 API도 부담이 커지기 때문입니다.

2022-05-30 01:57 UTC, lordmyshepherd commented on products/views.py
> +                    "new"          : True if product in Product.objects.all().order_by('-id')[:2] else False,
신상품 기준이 최근에 등록된 상품 기준으로 정렬해서 위에 최근 2개를 신상품으로 보는건가요?

2022-05-30 04:27 UTC, jhwang0801 commented on products/views.py
> +                        .order_by(sort_type.get(sort))[offset:offset+limit]
필수 구현해야하는 프로젝트 다 진행 후에 말씀해주신 부분들 고민해보도록 하겠습니다!!
감사합니다~!!

2022-05-30 04:31 UTC, jhwang0801 commented on products/urls.py
> +    path('/list', ProductListView.as_view()),
`products/list`라고 지정해 둔 이유는
애초에 저희가 클론코딩하는 오설록 웹사이트에서 제품 리스트의 엔드포인트를 따로 지정해두었기 때문이기도 합니다.

또한, 이후 진행한 제품 상세페이지의 엔드포인트를 지정하는 과정에서 `products`만을 사용하는 것보다 제품 리스트와 상세페이지에 각각의 엔드포인트를 지정해주는 것이 더 효과적이라 생각했습니다.

2022-05-30 04:34 UTC, jhwang0801 commented on products/views.py
> +            offset        = int(request.GET.get('offset',0))
감사합니다!!

2022-05-30 04:42 UTC, jhwang0801 commented on products/views.py
> +                    "new"          : True if product in Product.objects.all().order_by('-id')[:2] else False,
신상품에 대한 관리는 해당 회사의 비지니스모델에 따라 다양한 방법으로 관리된다고 알고있습니다.
신상품 테이블을 따로 만들어서 관리하는 등 다양한 방법이 있지만, 이번 프로젝트를 진행함에 있어서는 신상품에 대한 테이블을 따로 생성하지 않고 진행하기로 하였습니다.
또한` Product` 테이블에 신상품에 대한 Column을 추가하는 것은 좋지 않은 방법(메모리를 낭비하는 꼴)이라 사료되어 함수로 가장 최근에 등록된 상품 2개를 신상품으로 지정해주었습니다. (신상품을 관리하려는 목적보다는 프론트엔드에서 신제품 여부에 대한 값을 받아서 적용할 수 있게끔 하는 의도로 코드 작성하였습니다.)

2022-05-30 04:54 UTC, lordmyshepherd commented on products/urls.py
> +    path('/list', ProductListView.as_view()),
좋습니다!
오설록을 따라갈 필요는 없을 것 같아요!

대부분 엔드포인트를 만들 때, `products` 형태로 많이 사용합니다.
대표적인 예로 cafe24 api 문서를 참고해 보시면 좋을 것  같습니다.
https://developers.cafe24.com/docs/api/admin/#products
![스크린샷 2022-05-30 오후 1 53 54](https://user-images.githubusercontent.com/53214510/170919527-1056c132-5778-4f8d-9d40-bf611f7f0338.png)

2022-05-30 07:04 UTC, jhwang0801 commented on products/urls.py
> +    path('/list', ProductListView.as_view()),
멘토님 피드백 반영하여 링크 주신 api문서 확인 후 `path('', ProductListView.as_view()),`로 수정하였습니다!

2022-05-30 07:07 UTC, jhwang0801 commented
추가적으로 병민 멘토님께서 주셨던 추천상품 관련 피드백(Recommendation 관련하여,
ProductListView에 추가하여 관리 해볼 수 있도록 필수구현 과제 이후 진행해보도록 하겠습니다!!

2022-05-31 01:03 UTC, jhwang0801 commented
Feature/users Merge로 인하여 발생한 Conflicts들 모두 해결하였습니다!

2022-05-31 02:23 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-31 02:23 UTC, merged